# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c858938c5ff49fce2cabeded6ce0bf164818ff4a05965077d19249e541001d39be89576fc7584470dc0cc87494b7c71d7ffd6ae485f2b127dec620256f5fc18c

test:
  secret_key_base: ecff7666c7b68c4a9185769700512925f29f737c91ad9933926abf0a72b9596341cc3ffdb23d8abc664416d7ea05d68a9bfd4a955c1ae23330ff6b3e24373e6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
